server:
   type: 'Alpha'
   phase: 1
   mode: 'FirstStrike'
   loc: 'US'
   locnum: 1
regions:

players:

npcs:
   vendor_0:
      name: 'Template Vendor'
      msg: 'This is a template and isn't real.'
      items:
         - {id: 7, damage: 0, name: 'Plain ol\' bedrock.'}
         - {id: 5, damage: 1, name: 'Birch Planks.'}
            
