name: OldEdenPlugin_CORE
main: net.mayateck.OldEdenCore.OldEdenCore
version: 0.01

commands:
   money:
      description: Old Eden Economy commands.
      usage: /money <sub-command> <args>
      permission: eden.eco
      permission-message: 'Permission Error: You do not have access to that command.'
   alert:
      description: Old Eden Alerts.
      usage: /alert [type] [message]
      permission: eden.alert
      permission-message: 'Permission Error: You do not have access to that command.'
   eden:
      description: Old Eden Core Commands.
      usage: /eden [subcommand] <args>
      permission: eden.core
      permission-message: 'Permission Error: You do not have access to that command.'
   land:
      description: Old Eden region commands.
      usage: /land [subcommand] <args>
      permission: eden.land
      permission-message: 'Permission Error: You do not have access to that command.'

permissions:
   eden.*:
      description: 'Gives full access to Old Eden commands.'
      children:
         eden.alert: op
         eden.core: op
         eden.eco: true
   eden.alert:
      description: 'Allows access for the user to send server alerts.'
      children:
         eden.alert.sys: false
         eden.alert.note: op
         eden.alert.bcast: op
         eden.alert.err: false
   eden.eco:
      description: 'Old Eden economy.'
      children:
         eden.eco.pay: true
         eden.eco.set: op
         eden.eco.add: op
         eden.eco.check: true
         eden.eco.checkother: op
         eden.eco.subtract: op
   eden.land:
      description: 'Region definition commands.'
      children:
         eden.land.create: op
         eden.land.home: false
         eden.land.sethome: op
         eden.land.set: op
         eden.land.hop: op
